package tarkistus.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static tarkistus.syntymaAikaTarkistus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.07.31 01:19:52 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class syntymaAikaTarkistusTest {



  // Generated by ComTest BEGIN
  /** testKarkausvuosi27 */
  @Test
  public void testKarkausvuosi27() {    // syntymaAikaTarkistus: 27
    assertEquals("From: syntymaAikaTarkistus line: 28", 0, karkausvuosi(1900));
    assertEquals("From: syntymaAikaTarkistus line: 29", 0, karkausvuosi(1900));
    assertEquals("From: syntymaAikaTarkistus line: 30", 0, karkausvuosi(1901));
    assertEquals("From: syntymaAikaTarkistus line: 31", 1, karkausvuosi(1996));
    assertEquals("From: syntymaAikaTarkistus line: 32", 1, karkausvuosi(2000));
    assertEquals("From: syntymaAikaTarkistus line: 33", 0, karkausvuosi(2001));
    assertEquals("From: syntymaAikaTarkistus line: 34", 1, karkausvuosi(2004));
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTarkista51 */
  @Test
  public void testTarkista51() {    // syntymaAikaTarkistus: 51
    String s = "01:01:2000"; 
    assertEquals("From: syntymaAikaTarkistus line: 53", true, tarkista(s)); 
    s = "60:01:2000"; 
    assertEquals("From: syntymaAikaTarkistus line: 55", false, tarkista(s)); 
    s = "01:13:2000"; 
    assertEquals("From: syntymaAikaTarkistus line: 57", false, tarkista(s)); 
    s = "01:01:2030"; 
    assertEquals("From: syntymaAikaTarkistus line: 59", false, tarkista(s)); 
  } // Generated by ComTest END
}